# Default values for projet-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mssql:
  image: bart120/yv-database
  imageTag: 1
  mssqlSpec:
    port: 1433
    targetPort: 1433

redis:
  image: redis
  redisSpec:
    port: 6379
    targetPort: 6379

rabbitmq:
  image: rabbitmq
  imageTag: 3-management
  rabbitmqSpec:
    port: 15672
    targetPort: 15672
    port2: 5672
    targetPort2: 5672

elasticsearch:
  image: elasticsearch
  imageTag: 7.14.2
  elasticsearchSpec:
    port: 9200
    targetPort: 9200

kibana:
  image: kibana
  imageTag: 7.14.2
  kibanaSpec:
    port: 5601
    targetPort: 5601 
  env:
    elasticsearchHosts: "http://elasticsearch:9200"
    elasticsearchUrl: "http://elasticsearch:9200"
    elasticsearchServerBasePath: "/admin"

jobApi:
  image: fofanad97/projet-jobs-api
  imageTag: v1
  env:
    mssqlConectionJob: "Server=mssql-service;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;"

applicantsApi:
  image: fofanad97/projet-applicants-api
  imageTag: v1
  env:
    mssqlConectionApplicants: "Server=mssql-service;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"

identityApi:
  image: fofanad97/projet-identity-api
  imageTag: v1
  env:
    redisHost: redis-service:6379

web:
  image: fofanad97/projet-web
  imageTag: v1

replicaCount: 1

namespace: projet-cloud


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local