#service mssql
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: projet-cloud
spec:
  selector:
    app: mssql-pod
  ports:
    - port: 1433
      targetPort: 1433
  type: ClusterIP
---
#volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-volume
  namespace: projet-cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
#deployment mssql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: projet-cloud
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-pod
  template:
    metadata:
      labels:
        app: mssql-pod
    spec:
      containers:
      - image: fofanad97/projet-database:v1
        name: mssql
        ports:
        - containerPort: 1433
          name: mssql-port
        volumeMounts:
        - name: mssql-volume
          mountPath: /var/opt/mssql
        resources:
            requests:
              memory: 300Mi
              cpu: 250m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-volume
      restartPolicy: Always