apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: projet-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kibana:7.14.2
        name: kibana
        ports:
        - containerPort: 5601
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: SERVER_BASEPATH
            value: "/admin"

