apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: applicants-api
spec:
  selector:
    matchLabels:
      app: applicants-api-pod
  template:
    metadata:
      labels:
        app: applicants-api-pod
    spec:
      containers:
      - name: applicants-api
        image: "{{ .Values.applicantsApi.image }}:{{ .Values.applicantsApi.imageTag }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        env: 
        - name: ConnectionString
          value: {{ .Values.applicantsApi.env.mssqlConectionApplicants }}
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 1500Mi
            cpu: 1
      restartPolicy: Always