apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-pod
  template:
    metadata:
      labels:
        app: mssql-pod
    spec:
      containers:
      - image: "{{ .Values.mssql.image }}:{{ .Values.mssql.imageTag }}"
        name: mssql
        ports:
        - containerPort: {{ .Values.mssql.mssqlSpec.port }}
          name: mssql-port
        volumeMounts:
        - name: mssql-volume
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-volume
        persistentVolumeClaim:
          claimName: mssql-volume-claim
      restartPolicy: Always