apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: identity-api
spec:
  selector:
    matchLabels:
      app: identity-api-pod
  template:
    metadata:
      labels:
        app: identity-api-pod
    spec:
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - redis-pod
      #       topologyKey: "kubernetes.io/hostname"
      containers:
      - name: identity-api
        image: "{{ .Values.identityApi.image }}:{{ .Values.identityApi.imageTag }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        env: 
        - name: RedisHost
          value: {{ .Values.identityApi.env.redisHost }}
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 1500Mi
            cpu: 1
      restartPolicy: Always