apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: jobs-api
spec:
  selector:
    matchLabels:
      app: jobs-api-pod
  template:
    metadata:
      labels:
        app: jobs-api-pod
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mssql-pod
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: jobs-api
        image: "{{ .Values.jobApi.image }}:{{ .Values.jobApi.imageTag }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        env: 
        - name: ConnectionString
          value: {{ .Values.jobApi.env.mssqlConectionJob }}
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 1500Mi
            cpu: 1
      restartPolicy: Always