apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: logstash
spec:
  selector:
    matchLabels:
      app: logstash-pod
  template:
    metadata:
      labels:
        app: logstash-pod
    spec:
      containers:
      - image: "{{ .Values.logstash.image }}:{{ .Values.logstash.imageTag }}"
        name: logstash
        volumeMounts:
        - mountPath: /config/logstash.conf
          name: config
        command:
        - "logstash"
        - "-f"
        - "/config/logstash.conf"
      volumes:
      - name: config
        configMap:
          name: logstash-config
