apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
          - containerPort: {{ .Values.redis.redisSpec.port }}
        resources:
          requests:
            memory: 500Mi
            cpu: 4
      restartPolicy: Always