apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: projet-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: elasticsearch:7.14.2
        name: elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: discovery.type
          value: single-node
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        ports:
        - containerPort: 9200
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
