apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq-pod
  template:
    metadata:
      labels:
        app: rabbitmq-pod
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.imageTag }}"
        ports:
          - containerPort: {{ .Values.rabbitmq.rabbitmqSpec.port }}
          - containerPort: {{ .Values.rabbitmq.rabbitmqSpec.port2 }}
      restartPolicy: Always