apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch
    port: {{ .Values.elasticsearch.elasticsearchSpec.port }}
    targetPort: {{ .Values.elasticsearch.elasticsearchSpec.targetPort }}
  type: {{ .Values.service.type }}