apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: projet-cloud
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - port: 15672
      name: rabbitmq-port-1
      targetPort: 15672
    - port: 5672
      name: rabbitmq-port-2
      targetPort: 5672
  type: ClusterIP