apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - port: {{ .Values.rabbitmq.rabbitmqSpec.port }}
      name: rabbitmq-port-1
      targetPort: {{ .Values.rabbitmq.rabbitmqSpec.targetPort }}
    - port: {{ .Values.rabbitmq.rabbitmqSpec.port2 }}
      name: rabbitmq-port-2
      targetPort: {{ .Values.rabbitmq.rabbitmqSpec.targetPort2 }}
  type: {{ .Values.service.type }}