apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kibana
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.kibana.kibanaSpec.targetPort }}
  type: {{ .Values.service.type }}