apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: redis-pod
  ports:
    - port: {{ .Values.redis.redisSpec.port }}
      targetPort: {{ .Values.redis.redisSpec.targetPort }}
  type: {{ .Values.service.type }}