apiVersion: v1
kind: Service
metadata:
  name: applicants-api-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: applicants-api-pod
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}