apiVersion: v1
kind: Service
metadata:
  name: webmvc-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webmvc-pod
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}