apiVersion: v1
kind: Service
metadata:
  name: applicants-api-service
  namespace: projet-cloud
spec:
  selector:
    app: applicants-api-pod
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP