apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mssql-pod
  ports:
    - port: {{ .Values.mssql.mssqlSpec.port }}
      targetPort: {{ .Values.mssql.mssqlSpec.targetPort }}
  type: {{ .Values.service.type }}