apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness1
  namespace: projet-cloud
spec:
  containers:
  - name: applicants-api
    image: fofanad97/projet-applicants-api:v1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness2
  namespace: projet-cloud
spec:
  containers:
  - name: identity-api
    image: fofanad97/projet-identity-api:v1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness3
  namespace: projet-cloud
spec:
  containers:
  - name: jobs-api
    image: fofanad97/projet-jobs-api:v1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---   

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness4
  namespace: projet-cloud
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3-management
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---   

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness5
  namespace: projet-cloud
spec:
  containers:
  - name: redis
    image: redis
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---   

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness6
  namespace: projet-cloud
spec:
  containers:
  - name: webmvc
    image: fofanad97/projet-web:v1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness7
  namespace: projet-cloud
spec:
  containers:
  - name: mssql
    image: bart120/yv-database:1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5